name: Simple Staking v2.5 internal test bug report (until October 23rd)
description: This is an internal test on Sepolia Network to test upcoming features in simple staking service.
title: "[internal test - Contract Bugs]: "
labels: [internal-test-simple-staking-v2.5]
assignees:
  - Zena-park,zzooppii
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Make sure you are referencing [internal-test-(2024.10)](https://github.com/tokamak-network/ton-staking-v2/tree/internal-test-(2024.10)) branch. 
  - type: textarea
    id: Describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see! 
      value: "Describe the bug and its behavior! You can reference the problematic code using links (internal-test-(2024.10) branch)"
    validations:
      required: true
  - type: textarea
    id: Impact
    attributes:
      label: Impact
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: Exploit-Scenario-or-Demo
    attributes:
      label: Exploit Scenario
  - type: textarea
    id: Recommendation
    attributes:
      label: Recommendation
      description: If applicable, add screenshots to help explain your Recommendation.